name: Code Check & Test

on: [pull_request, push]

permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        name: Build & Test
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Update Homebrew Caches
              if: matrix.os == 'macos-latest'
              run: brew update

            - name: Install Neovim
              uses: rhysd/action-setup-vim@v1
              id: vim
              with:
                  neovim: true
                  # use latest stable version
                  # version: v0.9.0
            - name: npm install
              run: npm ci --silent

            - name: Build
              run: npm run test-compile

            - name: Webpack
              run: npm run webpack

            - name: Test
              uses: coactions/setup-xvfb@v1
              env:
                  NEOVIM_PATH: ${{ steps.vim.outputs.executable }}
                  NEOVIM_DEBUG: 1
                  NEOVIM_DEBUG_HOST: 127.0.0.1
                  NEOVIM_DEBUG_PORT: 4000
                  DBUS_SESSION_BUS_ADDRESS: ""
              with:
                  run: npm run test
    create:
        name: Create extension
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version: "18"
                  cache: "npm"
            - name: npm install
              run: npm ci --silent
            - name: Create extension
              run: npx vsce package -o vscode-neovim-${{github.sha}}.vsix
            - name: Upload extension
              if: runner.os == 'Linux'
              uses: actions/upload-artifact@v4
              with:
                  name: vscode-neovim
                  path: vscode-neovim-${{github.sha}}.vsix
    release-please:
        name: release-please
        if: ${{ github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  release-type: node
                  package-name: vscode-neovim
                  bump-minor-pre-major: true
                  changelog-types: >
                      [
                        { "type": "feat", "section": "Features", "hidden": false },
                        { "type": "fix", "section": "Bug Fixes", "hidden": false },
                        { "type": "docs", "section": "Documentation", "hidden": false },
                        { "type": "refactor", "section": "Refactor", "hidden": false },
                        { "type": "perf", "section": "Performance Improvements", "hidden": false }
                      ]
            - uses: actions/checkout@v5
              if: ${{ steps.release.outputs.release_created }}
            - uses: actions/setup-node@v6
              if: ${{ steps.release.outputs.release_created }}
              with:
                  node-version: "18"
                  cache: "npm"
            - name: npm install
              if: ${{ steps.release.outputs.release_created }}
              run: npm ci --silent
            - name: vsce package
              if: ${{ steps.release.outputs.release_created }}
              run: npx vsce package -o vscode-neovim-${{steps.release.outputs.tag_name}}.vsix
            - name: Upload Release Artifact
              if: ${{ steps.release.outputs.release_created }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run:
                  gh release upload ${{ steps.release.outputs.tag_name }} vscode-neovim-${{
                  steps.release.outputs.tag_name }}.vsix
            - name: vsce publish
              if: ${{ steps.release.outputs.release_created }}
              env:
                  VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish
